"""initial_schema

Revision ID: f2048f966ad9
Revises: 
Create Date: 2026-04-23 00:00:02.435027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f2048f966ad9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.create_unique_constraint('uq_product_categories_pair', 'product_categories', ['product_id', 'category_id'])
    op.alter_column('products', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tenants', 'api_key_hash',
               existing_type=sa.VARCHAR(length=64),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'api_key_hash',
               existing_type=sa.VARCHAR(length=64),
               server_default=sa.text('NULL::character varying'),
               existing_nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_constraint('uq_product_categories_pair', 'product_categories', type_='unique')
    op.alter_column('categories', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    # ### end Alembic commands ###
